 Product.create({"name" => "six dollars", "supplier_id" => "1", "price" => "5.99", "description" => "six dollars is now going for 5.99!" })
 Supplier.create({"name" => "multi-death-corporation", "email" => "mdc@fake.com", "phone_number" => "911"})
 Image.create({"url" => "blah blah blah", "product_id" => "1"})
Product.create({"name" => "99 cents", "supplier_id" => "2", "price" => "20.00" , "description" => "99 cents in one of our most popular product and goes great with any dollar amount." })
Supplier.create({"name" => "turtle sloth co.", "email" => "betheresoon@fake.com", "phone_number" => "9211"})
Image.create({"url" => "blobby blobby blah", "product_id" => "2" })
Product.create({"name" => "10%", "supplier_id" => "3", "price" => "5.29", "description" => "10 percent is a great purchase if you like taxes" })
Supplier.create({"name" => "corporation inc.", "email" => "corpinc@fake.com", "phone_number" => "921131"})
Image.create({"url" => "bob lob law", "product_id" => "3"})

